/*
 * generated by Xtext 2.14.0
 */
package org.xtext.domainmodel.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDomainModelScopeProvider extends DelegatingScopeProvider {
}
