/**
 * generated by Xtext 2.14.0
 */
package org.xtext.domainmodel.validation;

import org.xtext.domainmodel.validation.AbstractDomainModelValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DomainModelValidator extends AbstractDomainModelValidator {
}
