/*
 * generated by Xtext 2.14.0
 */
package org.xtext.domainmodel.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.domainmodel.ui.internal.DomainmodelActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DomainModelExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(DomainmodelActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		DomainmodelActivator activator = DomainmodelActivator.getInstance();
		return activator != null ? activator.getInjector(DomainmodelActivator.ORG_XTEXT_DOMAINMODEL_DOMAINMODEL) : null;
	}

}
