/*
 * generated by Xtext 2.14.0
 */
package org.xtext.domainmodel


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DomainModelStandaloneSetup extends DomainModelStandaloneSetupGenerated {

	def static void doSetup() {
		new DomainModelStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
