/**
 * generated by Xtext 2.14.0
 */
package org.xtext.domainmodel;

import org.xtext.domainmodel.DomainModelStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DomainModelStandaloneSetup extends DomainModelStandaloneSetupGenerated {
  public static void doSetup() {
    new DomainModelStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
