/**
 * generated by Xtext 2.14.0
 */
package org.xtext.domainmodel;

import org.xtext.domainmodel.AbstractDomainModelRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DomainModelRuntimeModule extends AbstractDomainModelRuntimeModule {
}
