/**
 * generated by Xtext 2.14.0
 */
package org.xtext.domainmodel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.domainmodel.ui.AbstractDomainModelUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DomainModelUiModule extends AbstractDomainModelUiModule {
  public DomainModelUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
