/**
 * generated by Xtext 2.14.0
 */
package org.xtext.domainmodel.ui.contentassist;

import org.xtext.domainmodel.ui.contentassist.AbstractDomainModelProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DomainModelProposalProvider extends AbstractDomainModelProposalProvider {
}
