/**
 * generated by Xtext 2.14.0
 */
package org.xtext.domainmodel.ide;

import org.xtext.domainmodel.ide.AbstractDomainModelIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DomainModelIdeModule extends AbstractDomainModelIdeModule {
}
