/**
 * generated by Xtext 2.14.0
 */
package org.xtext.domainmodel.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.domainmodel.DomainModelRuntimeModule;
import org.xtext.domainmodel.DomainModelStandaloneSetup;
import org.xtext.domainmodel.ide.DomainModelIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class DomainModelIdeSetup extends DomainModelStandaloneSetup {
  @Override
  public Injector createInjector() {
    DomainModelRuntimeModule _domainModelRuntimeModule = new DomainModelRuntimeModule();
    DomainModelIdeModule _domainModelIdeModule = new DomainModelIdeModule();
    return Guice.createInjector(Modules2.mixin(_domainModelRuntimeModule, _domainModelIdeModule));
  }
}
